### ISSUE TITLE
pkg::match_op() xbps-remove needs -R flag

### ISSUE THREAD

**Issue by bladedvox** [Phate6660/dep-organizer#1]
Basically for 2 reasons:
1. On line 52, if `args` has 0 length, the program crashes.
2. `-R` flag is the reverse of a regular `xbps-install` as it uninstalls dependencies not required by other packages or not installed explicitly (ie manually).

**Comment by Phate6660** [comment]
And fixed both issues, committing in a bit.

I solved reason one by moving the for loop used for pushing to the args above
the `arg[0]` check, that way there will never be an empty vector.

And I added the `-R` to the `xbps-remove` command.

By the way, does `xbps-install` only need `-S`, or should I add other flags
too?
