### ISSUE TITLE
xbps output is incomplete

### ISSUE THREAD

**Issue by bladedvox** [Phate6660/dep-organizer#2]
I'm guessing it needs `stderr` in addition to `stdout` to give the complete output. I tried my hand by doing this in the top of `pkg.rs`:

```
use std::io::{stdout, stderr, Write};
use std::process::{exit, Stdio};

fn run(cmd: &str, args: &[&str], message: &str) {
    let child = std::process::Command::new(cmd)
        .args(args)
        .stdin(Stdio::inherit())
        .stdout(Stdio::inherit())
        .stderr(Stdio::inherit())
        .output()
        .expect(message);
    stdout().write_all(&child.stdout).unwrap();
    stderr().write_all(&child.stderr).unwrap();
}
```
But of course I have no idea what I'm doing w/r/t Rust so it didn't work :p

**Comment by Phate6660** [comment]
You were actually pretty close (from what I can tell re-looking at `std::process::Command`'s docs) :)

Also wanted to let you know that I've seen both issues and am working on them
right now.

**Comment by bladedvox** [comment]
Verified fixed :)
