### ISSUE TITLE
write: appends to existing file

### ISSUE THREAD

**Issue by bladedvox** [Phate6660/dep-organizer#3]
Perhaps an ammend option would be in order to avoid duplicating dependee entries and allow removal of those which are no longer needed?

**Comment by Phate6660** [comment]
That's a good idea which gave me another idea.

- Write will create and write the full of contents of the file if non-existent, otherwise append (unchanged)
- Create an ammend operation like you said, which scans for any duplicates and removes them
- Rename the remove command to uninstall
- Create a remove operation, which will remove the said dependee packages from the file

**Comment by Phate6660** [comment]
Got 1 2 and 3 done. Gonna work on the 4th in a bit.

**Comment by Phate6660** [comment]
Just a friendly ping @bladedvox to see how you feel about what was done.

**Comment by bladedvox** [comment]
Hey, sorry I haven't had a chance to look at it yet, but I will see if I can give it a whirl tonight!

**Comment by bladedvox** [comment]
Sorry it took me a while to get to it, but I just tried it and it works great! I think maybe instead of having `ammend` be a command line option it should just perform that operation at the end of a `write`. Other than that, it's pretty solid!

**Comment by Phate6660** [comment]
I just really don't like automatically doing stuff like that though.
What if I added a command line arg to `write` to tell the program to `ammend` after writing?

**Comment by bladedvox** [comment]
Yeah, I mean I don't see the harm if the lines are complete duplicates, but yeah that would be fine too :P

**Comment by Phate6660** [comment]
There shouldn't be any harm.
I'm just paranoid and panicky when it comes to automation.
I pretty much despise it.

**Comment by Phate6660** [comment]
@bladedvox how does it look now?

**Comment by bladedvox** [comment]
Looks legit to me!

**Comment by Phate6660** [comment]
That's nice to know. Thanks! Closing this now.
If there are any other features you can think of that you'd want, please don't hesitate to open any more issues. :)
